Engine poc
shawn-hurley/jsonrpc-golang pull request #5
Opened 2022-09-20 21:05 UTC by shawn-hurley

2022-09-26 18:57 UTC, fabianvf requested changes

2022-09-26 18:57 UTC, fabianvf commented on engine/conditions.go
> +type Conditional struct {
Not sure I follow the separation between logical conditions and the innercondition, could or/and not be implemented as InnerConditions whose `Evaluate` method calls the `Evaluate` methods of the subconditions?

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +	conditionResponse InnerConndtionResponse
```suggestion
	conditionResponse InnerConditionResponse
```

2022-09-26 18:57 UTC, fabianvf commented on engine/conditions.go
> +type InnerConndtionResponse struct {
```suggestion
type InnerConditionResponse struct {
```

2022-09-26 18:57 UTC, fabianvf commented on engine/conditions.go
> +	Evaluate() (InnerConndtionResponse, error)
```suggestion
	Evaluate() (InnerConditionResponse, error)
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +func processRule(rule Rule) (InnerConndtionResponse, error) {
```suggestion
func processRule(rule Rule) (InnerConditionResponse, error) {
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +		//IF there is an inner conndtion here, that means there is only a single condition to run.
```suggestion
		//IF there is an inner condition here, that means there is only a single condition to run.
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +			return InnerConndtionResponse{}, fmt.Errorf("invalid when condition")
```suggestion
			return InnerConditionResponse{}, fmt.Errorf("invalid when condition")
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +func evaluateAndCondtions(conditions []Condition) (InnerConndtionResponse, error) {
```suggestion
func evaluateAndCondtions(conditions []Condition) (InnerConditionResponse, error) {
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +		return InnerConndtionResponse{}, fmt.Errorf("condtions must not be empty while evaluationg")
```suggestion
		return InnerConditionResponse{}, fmt.Errorf("condtions must not be empty while evaluationg")
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +	fullResponse := InnerConndtionResponse{Passed: true}
```suggestion
	fullResponse := InnerConditionResponse{Passed: true}
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +			var response InnerConndtionResponse
```suggestion
			var response InnerConditionResponse
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +func evaluateOrConditions(conditions []Condition) (InnerConndtionResponse, error) {
```suggestion
func evaluateOrConditions(conditions []Condition) (InnerConditionResponse, error) {
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +			var response InnerConndtionResponse
```suggestion
			var response InnerConditionResponse
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +				return InnerConndtionResponse{}, err
```suggestion
				return InnerConditionResponse{}, err
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +	return InnerConndtionResponse{}, nil
```suggestion
	return InnerConditionResponse{}, nil
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine_test.go
> +func (t testInerCondition) Evaluate() (InnerConndtionResponse, error) {
```suggestion
func (t testInnerCondition) Evaluate() (InnerConditionResponse, error) {
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine_test.go
> +type testInerCondition struct {
```suggestion
type testInnerCondition struct {
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine_test.go
> +	return InnerConndtionResponse{Passed: t.ret}, t.err
```suggestion
	return InnerConditionResponse{Passed: t.ret}, t.err
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine_test.go
> +	return &testInerCondition{
```suggestion
	return &testInnerCondition{
```

2022-09-26 18:57 UTC, fabianvf commented on provider/provider.go
> +func (p *ProviderCondition) Evaluate() (engine.InnerConndtionResponse, error) {
```suggestion
func (p *ProviderCondition) Evaluate() (engine.InnerConditionResponse, error) {
```

2022-09-26 18:57 UTC, fabianvf commented on provider/provider.go
> +		return engine.InnerConndtionResponse{}, err
```suggestion
		return engine.InnerConditionResponse{}, err
```

2022-09-26 18:57 UTC, fabianvf commented on provider/provider.go
> +	return engine.InnerConndtionResponse{
```suggestion
	return engine.InnerConditionResponse{
```

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +	// Only allow for 10 rules to be processed at once.
why?

2022-09-26 18:57 UTC, fabianvf commented on engine/engine.go
> +				responses = append(responses, response)
What happens to these responses?

2022-09-26 18:57 UTC, fabianvf commented on engine/engine_test.go
> +		// {
Why are these disabled?

2022-09-26 18:57 UTC, fabianvf commented on examples/java/.metadata/.log
> +!SESSION 2022-08-22 11:34:46.747 -----------------------------------------------
uncommit this I think

2022-09-26 18:57 UTC, fabianvf commented on examples/java/.metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.version
> +
probably should uncommit a lot of these files and add them to .gitignore

2022-09-26 18:57 UTC, fabianvf commented on main.go
> +	SETTING_FILE_PATH = "/home/shurley/repos/jsonrpc-golang/provider_settings.json"
probably should make this configurable pre-merge

2022-09-26 18:57 UTC, fabianvf commented on main.go
> +	// Now that we have all the providers, we need to start them.
Do we want to start them now, or start them once we know which providers are actually referenced in the rules?

2022-09-26 18:57 UTC, fabianvf commented on parser/rule_parser.go
> +// This will
will what

2022-09-26 18:57 UTC, fabianvf commented on parser/rule_parser.go
> +		// Rule's right now only contain two top level things, message and when.
```suggestion
		// Rules right now only contain two top level things, message and when.
```

2022-09-26 18:57 UTC, fabianvf commented on parser/rule_parser.go
> +func (r *RuleParser) LoadRules(filepath string) ([]engine.Rule, error) {
could also return a list of used providers so we know what we need to start?

2022-09-26 18:57 UTC, fabianvf commented on parser/rule_parser.go
> +		message, ok := ruleMap["message"].(string)
Assume this is a placeholder for now as we'll likely have more structured actions at some point, probably worth a TODO if so

2022-09-26 18:57 UTC, fabianvf commented on provider/golang/provider.go
> +	query := "query"
assume we want the line above this

2022-09-26 18:57 UTC, fabianvf commented on provider/java/provider.go
> +	// Get
unfinished comment

2022-09-26 18:57 UTC, fabianvf commented on provider/java/provider.go
> +	cmd := exec.CommandContext(ctx, "/home/shurley/repos/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/bin/jdtls",
need to fix this hardcoded path

2022-09-26 18:57 UTC, fabianvf commented on provider/java/provider.go
> +	cmd := exec.CommandContext(ctx, "/home/shurley/repos/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/bin/jdtls",
probably needs to be part of the provider config?

2022-09-26 18:57 UTC, fabianvf commented on provider/java/provider.go
> +		fmt.Printf("HERE!!!!!! - %v", err)
remove these prints (or make the messages useful)

2022-09-26 18:57 UTC, fabianvf commented on provider/java/provider.go
> +// This can probably be shared between the two
which two?

2022-09-26 18:57 UTC, fabianvf commented on provider/java/provider.go
> +	//workspace/executeCommand '{"command": "io.konveyor.tackle.ruleEntry", "arguments": {"query":"*customresourcedefinition","project": "java"}}'
comment needs some elaboration

2022-09-26 18:57 UTC, fabianvf commented on provider/java/provider.go
> +	cmd := exec.CommandContext(ctx, "/home/shurley/repos/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/bin/jdtls",
looks like it already is, just need to use the value

2022-09-26 18:57 UTC, fabianvf commented on rules_bak/types.go
> -package rules
remove this?

2022-09-26 20:23 UTC, shawn-hurley commented on engine/engine.go
> +	// Only allow for 10 rules to be processed at once.
This should be changed to only allow for 10 rules to being waiting at once

2022-09-26 20:23 UTC, shawn-hurley commented on engine/engine.go
> +				responses = append(responses, response)
for now, nothing, we don't have any output format for this

2022-09-26 20:23 UTC, shawn-hurley commented on engine/engine_test.go
> +		// {
🤦🏻‍♂️

2022-09-26 20:23 UTC, shawn-hurley commented on examples/java/.metadata/.log
> +!SESSION 2022-08-22 11:34:46.747 -----------------------------------------------
think I want todelete this whole thing

2022-09-26 20:23 UTC, shawn-hurley commented on examples/java/.metadata/.log
> +!SESSION 2022-08-22 11:34:46.747 -----------------------------------------------
and add to git ignore like you mentioned

2022-09-26 20:23 UTC, shawn-hurley commented on main.go
> +	SETTING_FILE_PATH = "/home/shurley/repos/jsonrpc-golang/provider_settings.json"
probably make it a relative path in the constants and then can add cobra and such as a followup? thoughts?

2022-09-26 20:23 UTC, shawn-hurley commented on parser/rule_parser.go
> +// This will
🤦🏻‍♂️

2022-09-28 17:11 UTC, shawn-hurley commented on engine/engine.go
> +				responses = append(responses, response)
adding todo at line 126 for this

2022-09-29 17:20 UTC, fabianvf requested changes

2022-09-29 17:20 UTC, fabianvf commented on engine/conditions.go
> +type ConndtionResponse struct {
hmm looks like the commit that fixed these was overwritten,  `ConndtionResponse` => `ConditionResponse`

2022-09-29 17:20 UTC, fabianvf commented on engine/conditions.go
> +		return ConndtionResponse{}, fmt.Errorf("condtions must not be empty while evaluationg")
`condtions` => `conditions` in the string

2022-09-29 17:20 UTC, fabianvf commented on engine/conditions.go
> +		// Short cirtcut loop if one and condition passes we can move on
s/and/or/

2022-09-29 17:20 UTC, fabianvf commented on engine/engine.go
> +	// Buffereed channel where Rule Processors are watching
`Buffereed` => `Buffered`

2022-09-29 17:20 UTC, fabianvf commented on examples/java/.project
> +<?xml version="1.0" encoding="UTF-8"?>
can this be deleted as well?

2022-09-29 17:20 UTC, fabianvf commented on examples/java/.classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Can this be deleted?

2022-09-29 17:20 UTC, fabianvf commented on examples/java/.settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
Can the .settings directory be removed + ignored?

2022-09-29 17:20 UTC, fabianvf commented on parser/rule_parser.go
> +// This will
will what tho

2022-09-29 17:20 UTC, fabianvf commented on provider/golang/provider.go
> +	query := "query"
bump

2022-09-29 17:50 UTC, shawn-hurley commented on provider/golang/provider.go
> +	query := "query"
fixed for real this time

2022-09-29 17:51 UTC, shawn-hurley commented on parser/rule_parser.go
> +// This will
updated for real this time

2022-09-29 19:23 UTC, merged